name    'tsuru-tsuru'
version '0.1.0'
source 'https://github.com/globocom/puppet-tsuru'
author 'Globo.com'
license 'BSD-style license that can be found in the LICENSE file'
summary 'Puppet module to Tsuru PaaS'
description 'Tsuru is an open source polyglot cloud application platform (PaaS). This package provides a complete and funcional Tsuru installation.'
project_page 'https://github.com/globocom/puppet-tsuru'

dependency 'puppetlabs/stdlib', '>= 2.5.0'
dependency 'puppetlabs/apt', '>=1.4.0'
